STATISTICHE_CLASSI = {
    "Guerriero": {
        "hp_max": 100,
        "danno_base": 15,
        "raggio_attacco": 2,
        "velocita_moltiplicatore": 1.0,
        "arma": "Spada",
        "has_mana": False,
        "desc_tasti": [
            "Click Sinistro: Attacco Spada (Raggio: 2, Danno: 15)",
            "Spazio: Rinforzo (Cura 15 HP, +30 Danno per 10 turni - 1 uso/stanza)",
        ],
        "abilita": {
            "nome": "Rinforzo",
            "tipo_cooldown": "stanza",
            "usi_max": 1,
            "durata": 10,
            "cura": 15,
            "danno_buff": 30,
        },
    },
    "Tank": {
        "hp_max": 150,
        "danno_base": 20,
        "raggio_attacco": 2,
        "velocita_moltiplicatore": 0.75,
        "arma": "Ascia",
        "has_mana": False,
        "desc_tasti": [
            "Click Sinistro: Attacco Ascia (Raggio: 1, Danno: 20)",
            "Spazio: Rinascita (Ripristina HP al massimo - 1 uso/partita)",
        ],
        "abilita": {
            "nome": "Rinascita",
            "tipo_cooldown": "partita",
            "usi_max": 1,
            "durata_invulnerabilita": 3,
        },
    },
    "Mago": {
        "hp_max": 60,
        "danno_base": 0,
        "raggio_attacco": 0,
        "velocita_moltiplicatore": 0.8,
        "arma": "Bastone",
        "has_mana": True,
        "mana_max": 100,
        "mana_rigenerazione_sec": 3,
        "desc_tasti": [
            "Tasto Q: Cura (+5 HP - Costo: 10 Mana)",
            "Tasto E: Repulsione (Spinge nemici a dist. 3 e infligge 2 Danno - Costo: 20 Mana)",
            "Spazio / Tasto R: Scia Oscura (Danno 15 a dist. 5 - Costo: 15 Mana)",
            "Click Destro / Tasto F: Fulmine (Danno 5 a dist. 5 - Costo: 10 Mana)",
        ],
        "incantesimi": {
            "Cura": {"costo_mana": 10, "cura": 5},
            "Repulsione": {
                "costo_mana": 20,
                "raggio_rilevamento": 3,
                "distanza_spinta": 6,
                "danno": 2,
                "distanza_boss": 4,
                "danno_boss": 0,
            },
            "Scia Oscura": {"costo_mana": 15, "distanza": 5, "danno": 15},
            "Fulmine": {
                "costo_mana": 10,
                "distanza": 5,
                "danno": 5,
                "durata_stun_sec": 3,
                "azioni_stun": 3,
            },
        },
    },
    "Assassino": {
        "hp_max": 70,
        "velocita_moltiplicatore": 1.25,
        "has_mana": False,
        "desc_tasti": [
            "Click Sinistro: Pugnale (Raggio: 1, Danno: 10, Crit: +40)",
            "Click Destro: Coltello da lancio (Raggio: 4, Danno: 3, Crit: +10)",
            "Spazio: Invisibilità (Invisibile ai nemici - Durata: 5 sec - 1 uso/stanza)",
            "Passiva: Lifesteal (+5 HP ad ogni uccisione)",
        ],
        "armi": {
            "Pugnale": {
                "raggio": 1,
                "danno_base": 10,
                "crit_prob": 0.10,
                "crit_danno": 40,
            },
            "Coltello da lancio": {
                "raggio": 4,
                "danno_base": 3,
                "crit_prob": 0.25,
                "crit_danno": 10,
            },
        },
        "abilita": {
            "nome": "Invisibilità",
            "tipo_cooldown": "stanza",
            "usi_max": 1,
            "durata": 5,
        },
    },
    "Mutaforma": {
        "hp_max": 100,
        "danno_base": 15,
        "raggio_attacco": 1,
        "velocita_moltiplicatore": 1.0,
        "has_mana": False,
        "desc_tasti": [
            "Click Sinistro: Attacco Forma Umana (Raggio: 1, Danno: 15)",
            "Spazio: Trasformazione nella Creatura scelta (Durata: 10 sec - 2 usi/partita)",
            "Click Destro: Abilità Speciale Creatura (Drago/Serpente/Centauro)",
        ],
        "abilita": {
            "nome": "Trasformazione",
            "tipo_cooldown": "partita",
            "usi_max": 2,
            "durata": 10,
        },
        "forme": {
            "Drago": {
                "danno": 25,
                "raggio": 2,
                "velocita_moltiplicatore": 0.8,
                "abilita_speciale": {
                    "nome": "Sputa Fuoco",
                    "raggio": 4,
                    "danno": 30,
                },
            },
            "Serpente Gigante": {
                "danno": 20,
                "raggio": 2,
                "velocita_moltiplicatore": 1.2,
                "abilita_speciale": {
                    "nome": "Sputa Veleno",
                    "raggio": 4,
                    "danno_immediato": 15,
                    "dox_danno_sec": 5,
                    "dot_durata": 4,
                },
            },
            "Centauro": {
                "danno": 20,
                "raggio": 2,
                "velocita_moltiplicatore": 1.5,
                "abilita_speciale": {
                    "nome": "Scatto",
                    "distanza": 4,
                    "danno_area": 20,
                },
            },
        },
    },
}